name: Build and Deploy WAR to Tomcat

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build WAR file
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build WAR file with Maven
        run: mvn clean install

      - name: Upload WAR as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-war
          path: target/*.war

      - name: Deploy to Remote Tomcat
        env:
          TOMCAT_HOST: 103.97.124.52
          TOMCAT_USER: admin
          TOMCAT_PASS: admin
        run: |
          curl -v -u $TOMCAT_USER:$TOMCAT_PASS \
            -T target/*.war \
            "http://$TOMCAT_HOST:8080/manager/text/deploy?path=/classmanagement&update=true"
