name: Java CI with Maven

on:
  push:
    branches: [trong-dev]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Run Unit Tests
        run: mvn clean test

      - name: Verify project
        run: mvn verify

      - name: Build WAR file
        run: mvn package

      - name: Upload WAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: servlet-war
          path: target/*.war
