name: CI/CD → Tomcat Deploy

on:
  push:
    branches: [ main, 'feature-*' ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Java 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Build WAR with Maven
        run: mvn clean package

      - name: Deploy WAR to Tomcat
        env:
          TOMCAT_USERNAME: admin
          TOMCAT_PASSWORD: admin123
          TOMCAT_HOST: your-domain.com  # 👈 Thay bằng host thật (KHÔNG PHẢI localhost)
          TOMCAT_PORT: 8080
        run: |
          curl -v -u $TOMCAT_USERNAME:$TOMCAT_PASSWORD \
            -T target/*.war \
            "http://$TOMCAT_HOST:$TOMCAT_PORT/manager/text/deploy?path=/baitapnhom5&update=true"
