name: Java CI/CD with Maven - Build and Deploy WAR

on:
  push:
    branches: [ main, 'feature-*' ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 📥 Checkout source
      uses: actions/checkout@v3

    - name: ☕ Set up Java 8
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '8'

    - name: 📦 Build WAR with Maven
      run: mvn clean package

    - name: 🚀 Deploy WAR to Tomcat
      env:
        TOMCAT_HOST: ${{ secrets.TOMCAT_HOST }}
        TOMCAT_USERNAME: ${{ secrets.TOMCAT_USERNAME }}
        TOMCAT_PASSWORD: ${{ secrets.TOMCAT_PASSWORD }}
      run: |
        curl -T target/*.war "http://$TOMCAT_USERNAME:$TOMCAT_PASSWORD@$TOMCAT_HOST:8080/manager/text/deploy?path=/baitapnhom5&update=true"
